language: python
python:
  - "3.7"
install:
  # TODO: requirements.txt
  - pip install pyspark pandas luigi pyspark-stubs eliot
  # pip install jupyter jupytext
  - pip install mypy flake8 eliot-tree
script:
  - make
