# cribbed from
#  - https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml
#  - https://proandroiddev.com/automating-android-library-release-using-github-actions-c783e44ea216

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build fatjar package with JDBC drivers
        run: ./gradlew fatjar

      - name: Archive test report
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Archive jar package
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: build/libs/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/naaccr-tumor-data.jar
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

