# cribbed from https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml
# with release stuff added

name: Trial Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test/
    - name: Archive jar package
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: build/libs/
